### ISSUE TITLE
Could not find `trained PaSegNet path`

### ISSUE THREAD

**Issue by huboqiang** [Biooptics2021/PathFinder#2]
Hi, I am trying to analyze my HCC `.mrxs` data. I find PathFinder is very helpful tools to extract TumorMicroEnv information on HE so I try to use the code. 

But when I have a try, I find the  `PaSegNet model` was not provided. So could you please provide me a download link? Thanks!

**Comment by LiangJunhao-THU** [comment]
Hi @huboqiang - thanks for your interest! Sorry for the late reply and I just uploaded the trained model to the cloud disk.
The download link is: https://cloud.tsinghua.edu.cn/f/55144035daa84c13b0cf/?dl=1
Thank you for your question ;)
