### ISSUE TITLE
About the pretrained PaSegNet checkpoint

### ISSUE THREAD

**Issue by ZHAN-GAN** [Biooptics2021/PathFinder#3]
Hello, Dear authors, I was very impressed by this work, but when i try to reproduce your work, I could only find the checkpoint of MacroNet, I could not find the checkpoint of PaSegNet, could you kindly provide the checkpoint of PaSegNet? Thank you. Best regards.

**Comment by wzr0108** [comment]
looking forward to the checkpoint of PaSegNet, too

**Comment by LiangJunhao-THU** [comment]
Hi @ZHAN-GAN @wzr0108, Sorry for the late reply and thank you for your interest!
I have just uploaded the trained model to the cloud disk: https://cloud.tsinghua.edu.cn/f/55144035daa84c13b0cf/?dl=1
Thanks a lot for your question!
